export * from './eventHandlers';
export * from './flowCtl';
export * from './loco';
export * from './turnouts';

// 94 commands in total

// 19 down...
export const implementedCommands = [
    'AUTOMATION',
    'CLOSE',
    'DELAY',
    'ENDIF',
    'ENDTASK',
    'ESTOP',
    'FOFF',
    'FON',
    'FWD',
    'IFCLOSED',
    'IFTHROWN',
    'ONCLOSE',
    'ONTHROW',
    'REV',
    'ROUTE',
    'SEQUENCE',
    'SPEED',
    'STOP',
    'THROW',
];

// 75 to go
export const unimplementedCommands = [
    'ACTIVATE',
    'ACTIVATEL',
    'AFTER',
    'ALIAS',
    'AMBER',
    'AT',
    'ATGTE',
    'ATLT',
    'ATTIMOUT',
    'AUTOSTART',
    'BROADCAST',
    'CALL',
    'DEACTIVATE',
    'DEACTIVATEL',
    'DELAYMINS',
    'DELAYRANDOM',
    'DRIVE',
    'ELSE',
    'FADE',
    'FOLLOW',
    'FREE',
    'GREEN',
    'IF',
    'IFAMBER',
    'IFGREEN',
    'IFGTE',
    'IFLT',
    'IFNOT',
    'IFRANDOM',
    'IFRED',
    'IFRESERVE',
    'IFTIMEOUT',
    'INVERT_DIRECTION',
    'JOIN',
    'LATCH',
    'LCD',
    'LCN',
    'ONACTIVATE',
    'ONACTIVATEL',
    'ONDEACTIVATE',
    'ONDEACTIVATEL',
    'PAUSE',
    'PIN_TURNOUT',
    'POM',
    'POWEROFF',
    'POWERON',
    'PRINT',
    'READ_LOCO',
    'RED',
    'RESERVE',
    'RESET',
    'RESUME',
    'RETURN',
    'ROSTER',
    'SENDLOCO',
    'SERAIL1',
    'SERAIL2',
    'SERAIL3',
    'SERIAL',
    'SERVO_SIGNAL',
    'SERVO_TURNOUT',
    'SERVO',
    'SERVO2',
    'SET',
    'SETLOCO',
    'SIGNAL',
    'SIGNALH',
    'START',
    'TURNOUT',
    'UNJOIN',
    'UNLATCH',
    'VIRTUAL_TURNOUT',
    'WAITFOR',
    'XFOFF',
    'XFON',
];
